
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <i class="fa fa-rupee"><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></i>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <i class="fa fa-rupee"><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></i>
    </td>
</tr>
<?php else:?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <i class="fa fa-rupee"><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></i>
    </td>
</tr>
<?php endif;?>
