<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $theme = $this->helper('ultimo'); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view nested-container" itemscope itemtype="http://schema.org/Product">
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<div class="no-display">
    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
    <input type="hidden" name="related_product" id="related-products-field" value="" />
  </div>
  	<?php echo $this->getChildHtml('media') ?>
  	<div class="col-sm-6 margin-top-30 col-xs-12 single-product-detail">
  		<div class="row">
  			<div class="col-sm-6 col-xs-12">
  				<ul class="tabs clearfix">
					<li>
                    	<input type="radio" name="tabs" id="tab1" checked />
                        <label for="tab1" class="tab-label">Details &amp; Shopping</label>
                        <div id="tab-content1" class="tab-content">
                          <div class="product-name" itemscope itemtype="http://schema.org/Product">
                            <h3 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>
                          </div>
                          <?php //echo $this->getReviewsSummaryHtml($_product, 'aggregate', true); //be the first to review ?>
                          <p>
                            <?php if ($_product->getShortDescription()){ ?>
                          <div class="short-description">
                            <div class="std" itemprop="description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                          </div>
                          <?php }?>
                          <span class="strong">Details:</span> <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?> <br />
                          <span class="strong">SKU:</span> <?php echo $_product->getSku();?>
                          </p>
                          <div class="margin-top-20">
<?php 
if (!$this->hasOptions()){ //add to cart when no options for SP
	if($_product->isSaleable()){ 
		echo $this->getChildHtml('addtocart');
	} 
	echo $this->getChildHtml('extra_buttons');
}
?>

<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
<div class="box-additional grid-full">
  <div class="container2-wrapper"><?php echo $container2_html; ?></div>
</div>
<?php endif; ?>
<?php endif; ?>
                            <a class="btn button-orange button--wayra btn-popup" href="#popup1">Bulk Enquiry</a> </div>
                        </div>
                    </li>
					<!--review form-->
  					<li>
                        <input type="radio" name="tabs" id="tab2" />
                        <label for="tab2" class="tab-label">Reviews</label>
                        <div id="tab-content2" class="tab-content">
                        <h3>Write Your Review</h3>
                      <form>
                        <div class="form-group">
                          <label for="name">Your Name</label>
                          <input type="text" class="form-control" id="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                          <label for="email">Email</label>
                          <input type="email" class="form-control" id="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                          <label for="customer-review">Your Review</label>
                          <textarea class="form-control" id="customer-review" placeholder="Review">
                    </textarea>
                        </div>
                        <button type="submit" class="btn button-orange button--wayra">Submit</button>
                      </form>
                    </div>
                    </li>
				</ul>
			</div>
			<div class="col-sm-6 col-xs-12">
              <div class="product-option price-options clearfix">
                <div class="border-bottom-light clearfix">
                  <div class="prices pull-left">
                    <dl class="primary clearfix">
                      <dt class="wl-access-aid">Price:</dt>
                      <?php echo $this->getChildHtml('product_type_data'); ?>
                      <dd class="price"> <sup>Rs.</sup><span class="rupee">6,518</span><sup class="cents">.16</sup> </dd>
                    </dl>
                  </div>
                  <?php //die;?>
                  <div class="pull-right text-right"> <a href="#" class="btn button-orange button--wayra btn-sm"> <span class="wl-button wl-button--simple">AVAILABILITY</span> </a> </div>
                </div>
                
	<?php
    if ($_product->isSaleable() && $this->hasOptions()){ // add to cart for CP
        if ($container1_html = $this->getChildChildHtml('container1', '', true, true)){ ?>
    <div class="container1-wrapper"><?php echo $container1_html; ?></div>
    <?php }
    }?>

	<div class="select-size padding-top-20">
      <div class="clearfix">
        <div class="pull-left">Select a size</div>
        <div class="pull-right text-right"> <a href="#" class="btn button-orange button--wayra btn-sm">CHART</a> </div>
      </div>
      <ul class="list-inline">
        <li><a href="#">XS</a></li>
        <!--
-->
        <li><a href="#">S</a></li>
        <!--
-->
        <li><a href="#">M</a></li>
        <!--
-->
        <li><a href="#">L</a></li>
      </ul>
    </div>
                
                <?php //die;?>
              </div>
            </div>
		</div>
	</div>
	<div class="col-sm-2 col-xs-12 margin-top-30 related-product">
  <ul class="list-group">
    <li class="list-group-item"><i class="fa fa-plane"></i><span>We will send this product in 7 days.</span></li>
    <li class="list-group-item"><i class="fa fa-mobile-phone"></i><span>Call us now for more info about our products.</span></li>
    <li class="list-group-item"><i class="fa fa-arrow-left"></i><span>Return purchased items and get all your money back.</span></li>
  </ul>
  <?php echo $this->getChildHtml('related_products');?> </div>
<?php
        //echo $this->getChildHtml('extrahint');
        //echo $this->getChildHtml('info_tabs');
        /*echo $this->getChildHtml('product_additional_data');
		echo $this->getTierPriceHtml(); //tier prices
		//echo $this->getChildHtml('sharing');
		echo $this->getChildHtml('alert_urls'); //alerts
		echo $this->getChildHtml('other');
		echo $this->getChildHtml('additional');*/
		?>
</form>
	<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
</div>
<!-- end: product-view --> 

<!--bulk enquiry form-->
<div id="popup1" class="overlay">
  <div class="popup">
    <h3 class="no-margin">For bulk enquiry</h3>
    <a class="close" href="#">&times;</a>
    <div class="content margin-top-20">
      <form class="form-horizontal">
        <div class="form-group row">
          <label for="userName" class="col-sm-2 control-label">Name</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="userName" placeholder="Your Name">
          </div>
        </div>
        <div class="form-group row">
          <label for="userContact" class="col-sm-2 control-label">Contact</label>
          <div class="col-sm-10">
            <input type="tel" class="form-control" id="userContact" placeholder="your Contact">
          </div>
        </div>
        <div class="form-group row">
          <label for="userEmail" class="col-sm-2 control-label">Email</label>
          <div class="col-sm-10">
            <input type="email" class="form-control" id="userEmail" placeholder="your Contact">
          </div>
        </div>
        <div class="form-group row">
          <label for="quantity " class="col-sm-2 control-label">Quantity</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="quantity" placeholder="Quantity">
          </div>
        </div>
        <div class="form-group row">
          <label for="product" class="col-sm-2 control-label">Product</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="product" placeholder="Product">
          </div>
        </div>
        <div class="form-group col-xs-12">
          <label for="moreOrder" class="control-label">Have more to order, write here</label>
          <textarea class="form-control"></textarea>
        </div>
        <div class="form-group col-xs-12">
          <button type="submit" class="btn button-orange button--wayra">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
