<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Shareme
 * @version    1.0.2
 * @copyright  Copyright (c) 2011-2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
/** @var Magpleasure_Shareme_Block_Checkout_Cart_Coupon $this */
?>
<form id="discount-coupon-form" action="<?php echo $this->getPostUrl(); ?>" method="post">
    <div class="discount">
        <h2><?php echo $this->__('Discount Codes') ?></h2>
        <div class="discount-form">
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupon" value="0" />
            <div class="input-box">
                <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
            </div>
            <?php if ($this->getShareMeCodes()->getSize()): ?>
            <div class="shareme-codes">
                <ul>
                <?php foreach ($this->getShareMeCodes() as $coupon): ?>
                    <li>
                        <div>
                            <span class="coupon-code"><?php echo $coupon->getCouponCode(); ?></span>
                            <span class="remove-button"><a title="<?php echo $this->__("Remove"); ?>" href="<?php echo $this->getRemoveUrl($coupon); ?>"><img alt="<?php echo $this->__("Remove"); ?>" src="<?php echo $this->getSkinUrl('shareme/images/close_btn.gif') ?>" /></a></span>
                        </div>
                    </li>
                <?php endforeach; ?>
                </ul>
                <div class="clear"></div>
            </div>
            <?php endif; ?>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupon').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupon').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
};
//]]>
</script>
