<!--slider section start here-->
<div class="main-slider">
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/');?>pokyshop-women-collection.jpg" alt="pokyshop-women-collection" /></div>
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/');?>pokyshop-bedsheet.jpg" alt="pokyshop-bedsheet" /></div>
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/');?>pokyshop-gift.jpg" alt="pokyshop-gift" /></div>
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/');?>pokyshop-Vintage-Antiques.jpg" alt="pokyshop-Vintage-Antiques" /></div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"><i class="fa fa-angle-right fa-5x"></i></div>
    <div class="swiper-button-prev"><i class="fa fa-angle-left fa-5x"></i></div>
  </div>
</div>
<!--slider section end here-->



<!--main container section start here-->
<main class="cd-main-content">
  <div class="home-wrapper">
    <div class="new-collection container">
      <h1>What's New</h1>
      <div class="content">			
			<div id="hs_container" class="hs_container">
				<div class="hs_area hs_area1">
					<img class="hs_visible" src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area1/1.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area1/2.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area1/3.jpg" alt=""/>
				</div>
				<div class="hs_area hs_area2">
					<img class="hs_visible" src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area2/1.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area2/2.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area2/3.jpg" alt=""/>
				</div>
				<div class="hs_area hs_area3">
					<img class="hs_visible" src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area3/1.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area3/2.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area3/3.jpg" alt=""/>
				</div>
				<div class="hs_area hs_area4">
					<img class="hs_visible" src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area4/1.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area4/2.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area4/3.jpg" alt=""/>
				</div>
				<div class="hs_area hs_area5">
					<img class="hs_visible" src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area5/1.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area5/2.jpg" alt=""/>
					<img src="<?php echo $this->getSkinUrl('images/');?>hoverslide/area5/3.jpg" alt=""/>
				</div>
			</div>

			
		</div>
        <div class="margin-top-20">
        <img src="http://placehold.it/1140x300" alt="banner" class="img-responsive">
        </div>
    </div>
    
	<div class="about-section">
		<div class="container">
		<h1>About Us</h1>
		<p class="text-justify margin-top-20">Let&lsquo;s make it all in India and sell it to the world- is what we desire. At Pokyshop, we have taken the "Make in India" pledge far more seriously than you can imagine. Giving a platform to the new businesses, is one thing but then we wish to dig deep inside and get to the roots and explore what is lost. Confused? Let us simplify it for you- we wish to revive our handicrafts; not just of a State or two but of the entire nation. There is so much to be showcased to the world. Every State has its own treasures, hidden underneath, waiting to be explored.
We at Pokyshop make the most sincere efforts to revive the craftsmanship. There is such enormous diversity existing in India that most of us are simply clueless about the prevailing forms of art and craft. Jaipur blue pottery, the marbel art, madhubani paintings, chikankari, phulkari, nakshi kantha to name a handful. We might know of some really famous ones or about the ones in our State, but there is a plethora- unseen and hidden.</p>
<p class="text-justify">At Pokyshop, its our endeavor to promote as many handcrafted art as possible. We plan to set up a team that will focus on each State individually and bring out the prevalent handicraft for the world to see.</p>
<p class="text-justify">With this project, we not just bring the Indian handicrafts to the limelight but also contribute to the upliftment of craftsmen. Many of these craftsmen have skills which they have inherited, not everyone has the potential to practice such intricate art and still, they are being exploited. There are artifacts that take days and months of hard work and extensive labor to come to life. They are then sold at majestic prices in the international markets and all these poor craftsmen get is a megre amount for all their efforts.</p>
<p class="text-justify">We wish to revive their financial condition. We buy the products directly from them, paying the right value for their work, cutting off the middlemen and putting up these products online for sale. All traditional artifacts at one stop. This will also help the travelers and tourists to explore our country's heritage. They can browse through the website, select the State they wish to know about, look through the various handcrafted items and pick the ones they like- easy, convenient and pocket friendly.</p>
<p class="text-justify">In a nutshell- this project aims at boosting the economy, providing employment, supporting the craftsmen and promoting the Indian art and other Indian made products.
We feel proud to be a part of a nation with such immense diversity in all spheres. We take it to be our social responsibility to do something for the betterment of people who make India - "BHARAT".
If you wish to contribute to our endeavor and be benefited out of it feel free to contact us at <a href="#" class="text-black"><strong>www.pokyshop.com</strong></a></p>
<p class="text-justify">Not only the handicraft but you can manufacture anything from fashion to lifestyle and to jewelry and be a part of Pokyshop, we will give you the platform to sell your products. Buying and selling, all at one stop, Pokyshop!</p>
<h5>Let us Make in India :)</h5>

		</div>
	</div>
    <div class="swiper-parallax-container">
      <div class="parallax-bg" style="background-image:url(<?php echo $this->getSkinUrl('images/');?>parallax_slider.jpg)" data-swiper-parallax="-23%"></div>
      <div class="swiper-wrapper text-center">
        <div class="swiper-slide">
          <div class="subtitle" data-swiper-parallax="-200">Every day is a Fashion Show
            &amp; the world is the Runway</div>
        </div>
        <div class="swiper-slide">
          <div class="subtitle" data-swiper-parallax="-200">Every day is a Fashion Show
            &amp; the world is the Runway</div>
        </div>
        <div class="swiper-slide">
          <div class="subtitle" data-swiper-parallax="-200">Every day is a Fashion Show
            &amp; the world is the Runway</div>
        </div>
      </div>
      <!-- Add Pagination -->
      <div class="swiper-pagination swiper-pagination-white"></div>
    </div>
    <div class="color-2">
      <div class="container">
        <h1>We are social</h1>
        <div class="social-follow">
          <ul class="list-inline text-center">
            <li><a class="tooltip tooltip-effect-1" href="#"><span><i class="fa fa-facebook fa-3x"></i></span><span class="tooltip-content">Like On Facebook</span></a></li>
            <li><a class="tooltip tooltip-effect-1" href="#"><span><i class="fa fa-twitter fa-3x"></i></span><span class="tooltip-content">Follow On Twitter</span></a></li>
            <li><a class="tooltip tooltip-effect-1" href="#"><span><i class="fa fa-google-plus fa-3x"></i></span><span class="tooltip-content">Join us on Google Plus</span></a></li>
            <li><a class="tooltip tooltip-effect-1" href="#"><span><i class="fa fa-pinterest-p fa-3x"></i></span><span class="tooltip-content">Follow us on pinterest</span></a></li>
            <li><a class="tooltip tooltip-effect-1" href="#"><span><i class="fa fa-instagram fa-3x"></i></span><span class="tooltip-content">Follow us on instagram</span></a></li>
            <li><a class="tooltip tooltip-effect-1" href="#"><span><i class="fa fa-linkedin fa-3x"></i></span><span class="tooltip-content">Connect on linkedin</span></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</main>
<!--main container section start here-->
