<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="cart <?php echo $_priceDisplay; ?> cart-wrapper">
    <div class="padding-bottom-20 shopping-cart">
    	<?php echo $this->getMessagesBlock()->toHtml() ?>
    	<?php echo $this->getChildHtml('form_before') ?>
        
        <h2><?php echo $this->__('Shopping Cart') ?></h2>
        <?php /*?><?php if(!$this->hasError()): ?>
        <ul class="checkout-types top">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?><?php */?>        
        <div class="table-responsive margin-top-20">
    		<form action="<?php echo $this->getFormActionUrl() ?>" method="post">
				<?php echo $this->getBlockHtml('formkey'); ?>
                    <table id="shopping-cart-table" class="table cart-table data-table">
                      <tr>
                        <th></th>
                        <th><?php echo $this->__('Product Name') ?></th>
                        <th></th>
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <th><?php echo $this->__('Move to Wishlist') ?></th>
                        <?php endif ?>                
                        <th><?php echo $this->__('Unit Price') ?></th>
                        <th><?php echo $this->__('Qty') ?></th>
                        <th><?php echo $this->__('Subtotal') ?></th>
                        <th></th>
                      </tr>
                    <?php //	S:VA	Display Cart Items - cart/item/default.phtml
                        foreach($this->getItems() as $_item){ 
                            echo $this->getItemHtml($_item);
                        }
                    ?>
                    </table>              
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            </form>
    	</div>
		<?php /* Continue Shopping and Update Shopping Buttons 	*/?>
      	<div class="row">                        
        	<?php if($this->getContinueShoppingUrl()): ?>
            <div class="col-xs-12 col-xs-6">
          		<button type="button" class="btn btn-default no-bg" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')"><i class="fa fa-angle-double-left"></i> <?php echo $this->__('Continue Shopping') ?></button>
        	</div>
            <?php endif; ?>
            
        	<div class="col-xs-12 col-xs-6 text-right">
          		<button type="submit" name="update_cart_action" value="update_qty"  class="btn btn-default no-bg"><i class="fa fa-refresh"></i> <?php echo $this->__('Update Shopping Cart'); ?></button>
                
        	</div>
      	</div>
    </div>

	<?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
	
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('checkout_cart_widget') ?>
        
    <div class="row border-top-light">
		
        <div class="col-xs-12 col-sm-4 margin-top-20">
			<?php //	S:VA	Discount Coupon  - cart\shipping.phtml
            if (!$this->getIsVirtual()){
                echo $this->getChildHtml('shipping');
            }
            ?>
      	</div>
      
        <div class="col-xs-12 col-sm-4 margin-top-20">
			<?php //	S:VA	Discount Coupon  - cart\coupon.phtml
                echo $this->getChildHtml('coupon');
            ?>
        </div>
		
        <div class="col-xs-12 col-sm-4 margin-top-20 cart-section">
        	<?php //	S:VA	Cart Totals  - cart\totals.phtml
			echo $this->getChildHtml('totals');
			if(!$this->hasError()){
				foreach ($this->getMethods('methods') as $method){ 
					//	S:VA	checkout\onepage\link.phtml	
					//	S:VA	checkout\multishipping\link.phtml	
					if ($methodHtml = $this->getMethodHtml($method)){ 
						echo $methodHtml; 
					}
				}
			} 
			?>            
      	</div>
        
    </div>
    <?php echo $this->getChildHtml('checkout.cart.extra') ?>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>
