<?php if($crumbs && is_array($crumbs)): ?>
<ol class="breadcrumb" xmlns:v="http://rdf.data-vocabulary.org/#">		<?php // Added by Vaseem for Google Rich Snippets?>    
	<?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
        <li class="<?php echo $_crumbName ?><?php if($_crumbInfo['last']){echo ' active';}?>" typeof="v:Breadcrumb"><?php // Added by Vaseem for Google Rich Snippets?>
        <?php if($_crumbInfo['link']): ?>
            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
        <?php elseif($_crumbInfo['last']): ?>
            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
        <?php else: ?>
            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
        <?php endif; ?>
        <?php /*?><?php if(!$_crumbInfo['last']): ?>
            <span>/ </span>
        <?php endif; ?><?php */?>
        </li>
    <?php endforeach; ?>
</ol>
<?php endif; ?>
