<div class="cd-dropdown-wrapper"> <a class="cd-dropdown-trigger" href="#0">Menu</a>
  <nav class="cd-dropdown"> <a href="#0" class="cd-close">Close</a>
    <ul class="cd-dropdown-content">
      <li class="has-children"> <a href="#">Home Decor</a>
        <ul class="cd-secondary-dropdown is-hidden five-category">
          <li class="go-back"><a href="#0">Menu</a></li>
          <li class="see-all"><a href="#">All Home Decor</a></li>
          <li><a href="#">Blue pottery</a></li>
          <li><a href="#">Marble handicrafts</a></li>
          <li><a href="#">Handmade &amp; Wooden Crafts</a></li>
          <li><a href="#">Bedsheets</a></li>
          <li><a href="#">Home &amp; Kitchen Gifts</a></li>
        </ul>
        <!-- .cd-secondary-dropdown -->
      </li>
      <li><a href="#">Vintage &amp; Antiques</a></li>
      <li class="has-children"> <a href="#">Women</a>
        <ul class="cd-secondary-dropdown is-hidden three-category">
          <li class="go-back"><a href="#0">Menu</a></li>
          <li class="see-all"><a href="#">All Women</a></li>
          <li><a href="#">Footwear</a></li>
          <li><a href="#">Traditional Wear</a></li>
          <li class="has-children"> <a href="#">Fashion Accessories</a>
            <ul class="is-hidden">
              <li class="go-back"><a href="#0">Women</a></li>
              <li class="see-all"><a href="#">Fashion Accessories</a></li>
              <li><a href="#">Fashion Necklace</a></li>
              <li><a href="#">Fashion Earrings</a></li>
            </ul>
          </li>
        </ul>
        <!-- .cd-secondary-dropdown -->
      </li>
      <li class="has-children"> <a href="#">Festive Shop</a>
        <ul class="cd-secondary-dropdown is-hidden three-category">
          <li class="go-back"><a href="#0">Menu</a></li>
          <li class="see-all"><a href="#">All Festive Shop</a></li>
          <li><a href="#0">Sweets</a></li>
          <li><a href="#">Below 199</a></li>
          <li><a href="#">Dry Fruits</a></li>
        </ul>
        <!-- .cd-secondary-dropdown -->
      </li>
      <li><a href="#">Make in India</a></li>
    </ul>
    <!-- .cd-dropdown-content -->
  </nav>
</div>

<?php /*?><?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
<nav id="nav">
  <ol class="nav-primary">
    <?php echo $_menu ?> 
  </ol>
</nav>
<?php endif ?>
<?php */?>