<nav class="cd-nav">
  <ul id="cd-primary-nav" class="cd-primary-nav is-fixed">
    <li class="has-children"> <a href="#">Home Decor</a>
      <ul class="cd-secondary-nav is-hidden five-categories">
        <li class="go-back"><a href="#0">Menu</a></li>
        <li class="see-all"><a href="#">All Home Decor</a></li>
        <li><a href="#">Blue pottery</a></li>
        <li><a href="#">Marble handicrafts</a></li>
        <li><a href="#">Handmade &amp; Wooden Crafts</a></li>
        <li><a href="#">Bedsheets</a></li>
        <li><a href="#">Home &amp; Kitchen Gifts</a></li>
        <li> </li>
      </ul>
    </li>
    <li><a href="#">Vintage &amp; Antiques</a></li>
    <li class="has-children"> <a href="#">Women</a>
      <ul class="cd-secondary-nav is-hidden three-categories">
        <li class="go-back"><a href="#0">Menu</a></li>
        <li class="see-all"><a href="#">All</a></li>
        <li><a href="#">Footwear</a></li>
        <li><a href="#">Traditional Wear</a></li>
        <li class="has-children"> <a href="#">Fashion Accessories</a>
          <ul class="is-hidden">
            <li class="go-back"><a href="#0">Accessories</a></li>
            <li class="see-all"><a href="#">All Accessories</a></li>
            <li><a href="#">Fashion Necklace</a></li>
            <li><a href="#">Fashion Earrings</a></li>
          </ul>
        </li>
      </ul>
    </li>
    <li class="has-children"> <a href="#">Festive Shop</a>
      <ul class="cd-secondary-nav is-hidden three-categories">
        <li class="go-back"><a href="#0">Menu</a></li>
        <li class="see-all"><a href="#">All Festive Shop</a></li>
        <li><a href="#0">Sweets</a></li>
        <li><a href="#">Below 199</a></li>
        <li><a href="#">Dry Fruits</a></li>
      </ul>
    </li>
    <li><a href="#">Make in India</a></li>
  </ul>
  <!-- primary-nav --> 
</nav>

<?php /*?><?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
<nav id="nav">
  <ol class="nav-primary">
    <?php echo $_menu ?> 
  </ol>
</nav>
<?php endif ?>
<?php */?>