<div class="cd-dropdown-wrapper"> <a class="cd-dropdown-trigger" href="#0">Menu</a>
	<nav class="cd-dropdown"> <a href="#0" class="cd-close">Close</a>
    	<?php 
        $categoryId 		=	'2';	//	root category id of Default Category
        $categoryCollection = 	Mage::getModel('catalog/category')->load($categoryId);
        $levelOneCategoryArray	=	$categoryCollection->getChildrenCategories();
        if(count($categoryCollection) > 0) { ?>
        <?php if(count($levelOneCategoryArray) > 0) { ?>
                <ul class="cd-dropdown-content">
                  <?php foreach($levelOneCategoryArray as $key1) {
                    $categoryCollection2 	= 	Mage::getModel('catalog/category')->load($key1['entity_id']);
                    $levelTwoCategoryArray	= 	$categoryCollection2->getChildrenCategories()->toArray();
					$childCategoryCount		=	count($levelTwoCategoryArray);
                   ?>
                  <li <?php if( $childCategoryCount > 0) {?>class="has-children"<?php } ?>><a href="<?php echo $categoryCollection2->getUrl(); ?>"><?php echo $categoryCollection2->getName();?></a>
                    <?php 
					if( $childCategoryCount > 0) { ?>
                        <ul class="cd-secondary-dropdown is-hidden <?php echo digitsToNumber($childCategoryCount)?>-category">
                            <li class="go-back"><a href="#0">Menu</a></li>
                            <li class="see-all"><a href="<?php echo $categoryCollection2->getUrl(); ?>">All <?php echo $categoryCollection2->getName();?></a></li>
                            <?php foreach($levelTwoCategoryArray as $key2) {	
                                $categoryCollection3 		= 	Mage::getModel('catalog/category')->load($key2['entity_id']);
								$levelThreeCategoryArray	=	$categoryCollection3->getChildrenCategories()->toArray();
								$childCategoryCount2		=	count($levelThreeCategoryArray);
                            ?>
                            <li <?php if( $childCategoryCount2 > 1) {?>class="has-children"<?php } ?>><a href="<?php echo $categoryCollection3->getUrl(); ?>"><?php echo $categoryCollection3->getName(); ?></a>
							<?php 
                                if( $childCategoryCount2 > 0) { ?>
                                <ul class="is-hidden">
                                    <li class="go-back"><a href="#0"><?php echo $categoryCollection2->getName();?></a></li>
                                    <li class="see-all"><a href="<?php echo $categoryCollection3->getUrl(); ?>"><?php echo $categoryCollection3->getName(); ?></a></li>
                                    <?php foreach($levelThreeCategoryArray as $key3) {	
                                        $categoryCollection4 		= 	Mage::getModel('catalog/category')->load($key3['entity_id']);
                                    ?>
                                    <li><a href="<?php echo $categoryCollection4->getUrl(); ?>"><?php echo $categoryCollection4->getName(); ?></a></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                            </li>
                            <?php  }	?>
                        </ul>
                    <?php }	//	end if  ?>
                  </li>
                  <?php  }	// end foreach levelOneCategoryArray	?>
                </ul>
            <?php } //	end if ?>
        <?php } //	end if ?>
  	</nav>
</div>

<?php
function digitsToNumber($digit){
	switch ($digit) {
		case 1:
			return 'one';
			break;
		case 2:
			return 'two';
			break;
		case 3:
			return 'three';
			break;
		case 4:
			return 'four';
			break;
		case 5:
			return 'five';
			break;
		case 6:
			return 'six';
			break;
		default:
			return 'three';
			break;
	}
}
?>
<?php /*?><?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
<nav id="nav">
  <ol class="nav-primary">
    <?php echo $_menu ?> 
  </ol>
</nav>
<?php endif ?>
<?php */?>