<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Shareme
 * @version    1.0.2
 * @copyright  Copyright (c) 2011-2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Shareme_Block_Checkbox $this */
?>
<?php if ($this->canUse()): ?>
<div class="checkbox">
    <label for="<?php echo $this->getFieldId().$this->getAction(); ?>">
        <input class="request-input" type="checkbox" name="<?php echo $this->getFieldId().$this->getAction(); ?>" id="<?php echo $this->getFieldId().$this->getAction(); ?>"  />
        <?php echo $this->__("I like this product (%s)", $this->getDiscount()); ?>
    </label><br />
</div>
<?php endif; ?>