<?php
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>
<div id="esns_background_layer">
    <?php if ($this->getTheme() == 'default'): ?>
    <div id="esns_box_layer">
    	
		<div class="simple_inner" id="first-login-con">
  			<div class="close-link"><a href="#" id="esns_box_close">x</a></div>
  			
			<div class="logo"><img src="/skin/frontend/ultimo/default/images/logo.png" alt="pokyshop" /></div>
  			<span class="join-now">Join now for exclusive access to unique collections</span>
  			<div class="base-mini mini-newsletter">
    			<div class="borderClass">
                
                <div id="esns_box_subscribe_response_success"></div>
                
                    <form name="newsletter_subscribe_form" id="newsletter_subscribe_form" action="" method="post" onsubmit='return false'>
                    <fieldset class="content">
                        <label for="newsletter">Your email address:</label>
                        <input required id="esns_email" type="email" class="required-entry validate-email newsletter_input" name="email" placeholder="Enter Email Address">
                        
                        <div id="esns_box_subscribe_response_error"></div>
                        <div class="clearfix"></div>
                        <input id="" type="submit" align="middle" value="Subscribe" style="margin-top:-11px;">
                        <input id="esns_submit" name="fire_ajax" type="hidden" />
	        		</fieldset>
                    </form>
			    </div>
			</div>
  			<span class="already">Already a member? <a href="<?php echo Mage::getUrl('customer/account/login')?>">SIGN IN</a></span>
  			<div class="clr"></div>
		</div>
        
        <script type="text/javascript">
			var customForm = new VarienForm('newsletter_subscribe_form');
			jQuery('#newsletter_subscribe_form').submit(function() {
				//alert(customForm.validator.validate());
				if(customForm.validator.validate() === true) {
					jQuery("#esns_submit").trigger('click');
					//this.submit();
				}else{
					return false;
					jQuery("#esns_box_subscribe_response_error").hide();
				}
			});
		</script>


        <?php /*?><div id="esns_box_close"></div><?php */?>
        <?php /*?><div id="esns_box_title">
            <?php if ($this->getFirstTitle()): ?>
            <div id="esns_box_block_1">
               <?php echo $this->getFirstTitle() ?>
            </div>
            <?php endif; ?>
            <?php if ($this->getSecondTitle()): ?>
            <div id="esns_box_block_2">
                <?php echo $this->getSecondTitle() ?>
            </div>
            <?php endif; ?>
        </div><?php */?>

        <?php /*?><?php if ($this->getText()): ?>
        <div class="esns_box_lines"></div>
        <div id="esns_box_block_3">
            <?php echo $this->getText() ?>
        </div>
        <?php endif; ?><?php */?>
        <?php /*?><div class="esns_box_lines"></div>
        <div id="esns_box_subscribe"><?php */?>
            <?php /*?><div id="esns_box_subscribe_response_error"></div>
            <div id="esns_box_subscribe_response_success"></div><?php */?>
            <?php /*?><div id="esns_box_subscribe_form">
                <div id="esns_box_subscribe_input"><input onclick="if(this.value=='<?php echo $this->__('Email'); ?>') this.value=''" onblur="if(this.value=='') this.value='<?php echo $this->__('Email'); ?>'" id="esns_email123" name="subscribe_email" value="<?php echo $this->__('Email'); ?>" type="text"></div>
                <div id="esns_box_subscribe_submit"><a href="javascript:void(0)" id="esns_submit123" ><?php echo $this->__('Subscribe'); ?></a></div>
            </div>
        </div><?php */?>
    </div>
    <?php elseif($this->getTheme() == 'label'): ?>
    <div id="esns_box_layer" class="tl">
        <div id="esns_box_close"></div>


            <div id="esns_box_block_1">
                <?php echo $this->getFirstTitle() ?>
            </div>


            <div id="esns_box_block_2">
                <?php echo $this->getSecondTitle() ?>
            </div>



        <div id="esns_box_block_3">
            <?php echo $this->getText() ?>
        </div>

        <div id="esns_box_subscribe">
            <div id="esns_box_subscribe_response_error"></div>
            <div id="esns_box_subscribe_response_success"></div>
            <div id="esns_box_subscribe_form">
                <div id="esns_box_subscribe_input"><input onclick="if(this.value=='<?php echo $this->__('Email'); ?>') this.value=''" onblur="if(this.value=='') this.value='<?php echo $this->__('Email'); ?>'" id="esns_email" name="subscribe_email" value="<?php echo $this->__('Email'); ?>" type="text"></div>
                <div id="esns_box_subscribe_submit"><a href="javascript:void(0)" id="esns_submit" ><?php echo $this->__('Subscribe'); ?></a></div>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>