<h4><?php echo $this->__('Discount Codes') ?></h4>
<form id="discount-coupon-form" action="<?php echo $this->getFormActionUrl() ?>" method="post">
    <div class="form-group">
        <label for="coupon">Enter your coupon code if you have one.</label>
        <input class="input-text form-control" type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
    </div>
    
    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Apply')) ?>" class="btn btn-default no-bg" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply') ?>"><?php echo $this->__('Apply Coupon') ?></button>
	<?php if(strlen($this->getCouponCode())): ?>
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Cancel')) ?>" class="button2 cancel-coupon" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel') ?>"><?php echo $this->__('Cancel') ?></button>
    <?php endif;?>
</form>

<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>