<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
<?php else: ?>
    <div class="table-responsive">
		<table id="shopping-cart-totals-table">
			<?php echo $this->renderTotals('footer'); //	S:VA	Subs Total  - tax\checkout\grandtotal and subtotal.phtml?>
            <?php echo $this->renderTotals(); ?>
		</table>
    </div>
<?php endif; ?>
