<div class="inchoo-socialconnect-register">   
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if($this->_facebookEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> inchoo-socialconnect-register-facebook">
            <div class="fieldset">
                <?php /*?><h2 class="legend"><?php echo $this->__('Facebook Connect') ?></h2>
                <p><?php echo $this->__('You can register using your Facebook account.') ?></p><?php */?>
                <p><?php echo $this->getChildHtml('inchoo_socialconnect_checkout_facebook_button')?></p>
            </div>
        </div>
        <?php endif; ?>
		
		<?php if($this->_googleEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> inchoo-socialconnect-register-google">
            <div class="fieldset">
                <?php /*?><h2 class="legend"><?php echo $this->__('Google Connect') ?></h2>
                <p><?php echo $this->__('You can register using your Google account.') ?></p><?php */?>
                <p><?php echo $this->getChildHtml('inchoo_socialconnect_checkout_google_button')?></p>
            </div>
        </div>
        <?php endif; ?>
        
        <?php if($this->_twitterEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> inchoo-socialconnect-register-twitter">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Twitter Connect') ?></h2>
                <p><?php echo $this->__('You can register using your Twitter account.') ?></p>
                <p><?php echo $this->getChildHtml('inchoo_socialconnect_checkout_twitter_button')?></p>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_linkedinEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> inchoo-socialconnect-register-linkedin">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('LinkedIn Connect') ?></h2>
                <p><?php echo $this->__('You can register using your LinkedIn account.') ?></p>
                <p><?php echo $this->getChildHtml('inchoo_socialconnect_checkout_linkedin_button')?></p>
            </div>
        </div>
        <?php endif; ?>        
    </div>
</div>