<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct() ?>

<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php if ($_product->isAvailable()): ?>
    <p class="availability in-stock"><link itemprop="availability" href="http://schema.org/InStock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><link itemprop="availability" href="http://schema.org/OutOfStock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>
<?php echo $this->getPriceHtml($_product) ?>


<?php
//////////////////////////////////////////////////////////////////////////////
?>
<?php /*?>
<?php $_product = $this->getProduct() ?>
<?php if($_extraData = $this->getChildHtml('product_type_data_extra')): ?>
	<?php echo $_extraData; ?>
	<div class="mclear"></div>
<?php endif; ?>

<?php if ($_product->isAvailable() == false): ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
    <?php echo $this->getPriceHtml($_product) ?>
<?php endif; ?>
<?php */?>