<!-- Start home section -->

<div id="home"> 
  <!-- Start cSlider -->
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/') ?>pokyshop-incredible-india.gif" alt="pokyshop-incredible-india" /></div>
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/') ?>pokyshop-crafting-an-identity.jpg" alt="pokyshop-crafting-an-identity" /></div>
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/') ?>pokyshop--indian-crafts.jpg" alt="pokyshop--indian-crafts" /></div>
      <div class="swiper-slide"><img src="<?php echo $this->getSkinUrl('images/') ?>pokyshop-open-your-pokyShop.jpg" alt="pokyshop-open-your-pokyShop" /></div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"><i class="fa fa-angle-right fa-5x"></i></div>
    <div class="swiper-button-prev"><i class="fa fa-angle-left fa-5x"></i></div>
  </div>
</div>
<!-- End home section --> 
<!-- About us section start -->
<div class="section primary-section" id="about">
  <div class="container">
    <div class="about-text centered">
      <div class="title">
        <h1>About Us</h1>
        <p>Let&lsquo;s Redefine Entrepreneurship</p>
      </div>
      <p class="text-justify">Pokyshop.com is an online shopping start-up in its infancy. We offer a wide range of latest fashion apparels and lifestyle products to suit everyone&lsquo;s taste. Apart from that, what we have in store for you are the jewels of traditional Indian crafts such as Blue Pottery, Marble crafts, and Handicrafts. We are not just an online fashion site, 
        but we are also the sellers of the aforementioned craft products that haven&lsquo;t been able to come in light yet due to the unwillingness of any other site to sell them.</p>
      <p class="text-justify">Many hearts wonder why there is so much <strong>#MakeInIndia</strong> on a simple online shopping site, why there is a lot of hustle and bustle for "<strong>Sell on Pokyshop</strong>" instead of "<strong>Buy from Pokyshop</strong>". The answer to all this lies in the innate idea behind the evolution of Pokyshop to support young entrepreneurs by offering them a platform where they can realize their potential. This is a one stop shop for both the manufacturers and consumers to sell and buy a wide variety of products ranging from the latest fashion apparels to the jewels of traditional Indian crafts like Blue Pottery, Marble crafts, etc.</p>
      <p class="text-justify">So, if you are a budding designer, manufacturer, code developer, writer or even a thinker come and join hands with Pokyshop and we will provide you the stage for showcasing your talent because "<strong>Following brands is good, but making brands is even better</strong>".</p>
    </div>
  </div>
</div>
<!-- About us section end --> 
<!-- Why Us section start -->
<div class="section secondary-section" id="why">
  <div class="triangle"></div>
  <div class="container"> 
    <!-- Start title section -->
    <div class="title">
      <h1>Why Us?</h1>
      <!-- Section's title goes here -->
      <p>Let&lsquo;s Make Selling easier</p>
      <!--Simple description for section goes here. --> 
    </div>
    <p class="text-justify">If you are passionate about your craft or business we are passionate about selling it to the right people. We can help you sell to the world. Whether it's a small shop that you own or a large store, whether you run a small business from home or just have been thinking over getting up on your feet, we will support you!</p>
    <p>You no longer have to confine yourself in your locality. We can help you reach customers all over the world.</p>
    <p>If you that ability to create we have the ability to sell. So, don't just sell,<br>
      Let&lsquo;s pokyshop it!</p>
    <p>Let&lsquo;s redefine the way we do business.<br>
      Let&lsquo;s redefine entrepreneurship!<br>
    </p>
    <h3>#MakeInIndia</h3>
  </div>
</div>
<!-- Why Us section end --> 
<!-- store section start -->
<div id="store">
  <div class="section primary-section">
    <div class="triangle"></div>
    <div class="container">
      <div class="title">
        <h1>Open A Store</h1>
        <p>Turn Your Passion into a Business, Open a Pokystore Today.</p>
      </div>
      <p class="text-justify">If you are thinking of starting a business, we are here to support you in every way we can. We will showcase your products to target customers and do the rest for you.</p>
      <h3>Be your own boss!</h3>
      <p> Few Steps To Open your Pokystore.<br>
        Fill a seller form &amp; Submit.<br>
        Its done.<br>
      </p>
      <p>Our team will call you and will do the rest for you. Join Us Today By filling a Simple Form.<br>
        PokyShop enables the merchants to sell their products nationwide. You can avail PokyShop services like, Fulfillment, Marketing and Market Intelligence services. </p>
      <div class="pokystore-form" id="pokystore-form">
        <h3 class="text-center">Join Us</h3>
        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('inquiry/join_us.phtml')->toHtml();?> </div>
    </div>
  </div>
</div>
<!-- store section end -->
<div class="section secondary-section">
  <div class="triangle"></div>
  <div class="container centered">
    <p class="large-text">Let's redefine entrepreneurship <strong>Make In India</strong></p>
    <a href="#" class="button">Join now</a> </div>
</div>
<!-- sale section start -->
<div id="sale" class="section primary-section">
  <div class="triangle"></div>
  <div class="container">
    <div class="title">
      <h1>Seller form</h1>
    </div>
    <div class="pokystore-form animated" id="pokyseller-form"> <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('inquiry/sell_with_us.phtml')->toHtml();?> </div>
  </div>
</div>
<!-- sale section end --> 
<!-- Newsletter section start -->
<div class="section third-section">
  <div class="container newsletter">
    <div class="sub-section">
      <div class="title clearfix">
        <div class="pull-left">
          <h1>Newsletter</h1>
        </div>
      </div>
    </div>
    <div class="clearfix">
      <div class="col-md-6 col-sm-12 col-xs-12">
        <p class="large-text">Want to be our instant seller right now</p>
      </div>
      <div class="col-md-6 col-sm-12 col-xs-12">
        <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml();?>
      </div>
    </div>
  </div>
</div>
<!-- Newsletter section end --> 
<!-- Contact section start -->
<div id="contact" class="contact">
  <div class="section secondary-section">
    <div class="container">
      <div class="title">
        <h1>Contact Us</h1>
        <p>Get In Touch</p>
      </div>
      <div class="clearfix">
        <div class="col-md-5 col-xs-12 contact-form">
          <div id="successSend" class="alert alert-success invisible"> <strong>Well done!</strong>Your message has been sent.</div>
          <div id="errorSend" class="alert alert-error invisible">There was an error.</div>
          <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('inquiry/get_in_touch.phtml')->toHtml();?> </div>
        <div class="col-md-7 col-xs-12">
          <ul class="social">
            <li> <a href="https://www.facebook.com/pages/pokyshopcom/335131776671161"> <i class="fa fa-facebook"></i> </a> </li>
            <li> <a href="https://twitter.com/pokyshop"> <i class="fa fa-twitter"></i> </a> </li>
            <li> <a href="https://instagram.com/pokyshop/"> <i class="fa fa-linkedin"></i> </a> </li>
            <li> <a href="https://www.pinterest.com/pokyshop"> <i class="fa fa-pinterest"></i> </a> </li>
          </ul>
          <div class="mail-info"> Mail: <a href="mailto:sales@pokyshop.com">sales@pokyshop.com</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Contact section edn -->