<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * - Removed links to review page and review form
 */
?>
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <?php if ($this->getRatingSummary()):?>
        	<?php // Added by Vaseem for Google Rich Snippets?>
                <meta itemprop="ratingValue" content="<?php echo ($this->getRatingSummary()* .05); ?>">
                <meta itemprop="reviewCount" content="<?php echo $this->getReviewsCount(); ?>">
                <meta itemprop="bestRating" content="5">
                <meta itemprop="worstRating" content="1">
            <?php // Added by Vaseem for Google Rich Snippets?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <span class="amount"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><?php echo $this->__('Be the first to review this product') ?></p>
<?php endif; ?>
