<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Shareme
 * @version    1.0.2
 * @copyright  Copyright (c) 2011-2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Shareme_Block_Page $this */
?>
<iframe src="//www.facebook.com/plugins/likebox.php?href=<?php echo urlencode($this->getFacebookConfig('href')); ?>&amp;width=<?php echo $this->getFacebookConfig('width') - 20; ?>&amp;colorscheme=light&amp;show_faces=<?php echo $this->getFacebookConfig('faces') ? 'true' : 'false'; ?>&amp;border_color=<?php echo urlencode($this->getFacebookConfig('border_color')); ?>&amp;stream=<?php echo $this->getFacebookConfig('stream') ? 'true' : 'false'; ?>&amp;header=<?php echo $this->getFacebookConfig('header') ? 'true' : 'false'; ?>&amp;height=<?php echo $this->getFacebookConfig('height') - 55; ?>"
        scrolling="no"
        frameborder="0"
        style="border:none; overflow:hidden; width:<?php echo $this->getFacebookConfig('width') - 20; ?>px; height:<?php echo $this->getFacebookConfig('height') - 55; ?>px;"
        allowTransparency="true"></iframe>



