<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Shareme
 * @version    1.0.2
 * @copyright  Copyright (c) 2011-2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Shareme_Block_Shareme $this */
?>
<?php if ($this->somebodyActive()): ?>
<div class="shareme">
    <?php foreach ($this->_helper()->getElements() as $area): ?>
        <?php if ($this->_helper()->getConfig($area, "display")): ?>
            <?php echo $this->getElementHtml($area); ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <div class="actions" id="action_content">
        <?php foreach ($this->_helper()->getActions() as $area): ?>
            <?php echo $this->getElementHtml($area, 'action'); ?>
        <?php endforeach; ?>
        <?php if ($this->isSomebodyUsed()): ?>
            <?php if ($this->isLoggedIn()): ?>
            <div class="buttons">
                <div class="button">
                    <?php if ($this->canRequest()): ?>
                    <button onclick="showRequest(); return false;"
                            class="button"
                            title="<?php echo $this->__('I have shared. Give me the Coupon'); ?>"
                            type="button">
                        <span><?php echo $this->__('I have shared. Give me the Coupon'); ?></span>
                    </button>
                    <?php endif; ?>
                </div>
                <div class="info truncated">
                    <div class="truncated_full_value"><?php echo $this->getInfoHtml(); ?></div>
                    <a href="#" class="details" onclick="return false;" ><?php echo $this->__("Info"); ?></a>
                </div>
                <div class="clear"></div>
            </div>
            <?php else: ?>
            <div class="buttons">
                <div class="login-to-share"><span><?php echo $this->__("<a href='%s'>Log in</a> to create Coupon request", $this->getLoginUrl()); ?></span></div>
                <div class="info truncated">
                    <div class="truncated_full_value"><?php echo $this->getInfoHtml(); ?></div>
                    <a href="#" class="details" onclick="return false;" ><?php echo $this->__("Info"); ?></a>
                </div>
            </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php if ($this->canRequest()): ?>
    <div class="request" id="make_request" style="display: none;">
        <?php echo $this->getRequestHtml(); ?>
    </div>
    <?php endif; ?>
    <div class="clear"></div>
</div>
<?php endif; ?>
