<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<form action="<?php echo Mage::getUrl().'inquiry/index/joinus'; ?>" id="joinusForm" method="post" class="scaffold-form form-horizontal">
  <div class="form-group row">
    <label class="col-sm-4 control-label">Company Name:</label>
    <div class="col-sm-8">
      <input type="text" placeholder="Company Name" class="form-control input-text required-entry" name="company_name">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label">Company Description:</label>
    <div class="col-sm-8">&nbsp;</div>
  </div>
  <h4>Business Address (Main office)</h4>
  <div class="form-group row">
    <label class="col-sm-4 control-label">Address:</label>
    <div class="col-sm-8">
      <input type="text" placeholder="Address" class="input-text required-entry form-control" name="address">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label">City:</label>
    <div class="col-sm-8">
      <input placeholder="City" class="form-control input-text required-entry" value="" title="" name="city" id="city">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label">State:</label>
    <div class="col-sm-8">
      <?php	$stateCollection = Mage::getModel('directory/country')->load('IN')->getRegions()->toOptionArray(); ?>
      <?php if (count($stateCollection) > 0){ ?>
      <select name="state" id="state" class="form-control required-entry validate-select">
        <?php foreach($stateCollection as $state): ?>
        <option value="<?php echo $state['label']//$state['value'] ?>"><?php echo $state['label'] ?></option>
        <?php endforeach; ?>
      </select>
      <?php }else{ ?>
      <input name="state" id="state" title="" value="" class="input-text required-entry form-control"  placeholder="State"/>
      <?php } ?>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label">Postal Code:</label>
    <div class="col-sm-8">
      <input type="text" placeholder="Postal Code" class="form-control" name="postal_code">
    </div>
  </div>
  <h4>Contact Information</h4>
  <div class="form-group row">
    <label class="col-sm-4 control-label">Name:</label>
    <div class="col-sm-8">
      <input type="text" placeholder="Name" class="form-control input-text required-entry" value="" name="name">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label">Email Address:</label>
    <div class="col-sm-8">
      <input type="email" class="form-control input-text required-entry validate-email" value="" name="email" placeholder="Email Address" autocapitalize="off" autocorrect="off" spellcheck="false">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label">Phone Number:</label>
    <div class="col-sm-8">
      <input type="tel" placeholder="Phone Number" class="form-control input-text required-entry" value="" id="phone_no" name="phone_no">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 control-label"></label>
    <div class="col-sm-8 pull-right">
      <input type="submit" value="Submit" class="button">
    </div>
  </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var joinusForm = new VarienForm('joinusForm', true);
//]]>
</script> 
