<?php if($this->getItems()->getSize()){ ?>
    <ul class="list-inline">
        <li>People Who Viewed This Item Also Viewed</li>
    <?php foreach($this->getItems() as $_item){ ?>
        <li class="item"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(85) ?>" width="85" height="80" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
            <?php /*?><div class="product-details">
                <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
                <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                <?php endif; ?>
            </div><?php */?>
        </li>
    <?php }?>
    </ul>
<?php } ?>
